# Generated by Django 5.0.3 on 2025-02-18 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_contactinfo_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='map',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
