# Generated by Django 5.0.3 on 2025-02-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_contactinfo_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='subject',
            field=models.CharField(default='unknown', max_length=500),
        ),
    ]
